export const names = [
  "edo",
  "rizqi",
  "rio",
  "dika",
  "bocchi",
  "nigga",
  "xi",
  "ganjar",
  "anies",
  "prabowo",
  "Ayu",
  "Bella",
  "Citra",
  "Dewi",
  "Eka",
  "Fira",
  "Gita",
  "Hana",
  "Indah",
  "Jasmine",
  "Kartika",
  "Lia",
  "Mila",
  "Nina",
  "Olive",
  "Putri",
  "Qistina",
  "Rina",
  "Sari",
  "Tina",
  "Adit",
  "Bimo",
  "Cakra",
  "Damar",
  "Eko",
  "Fajar",
  "Ghani",
  "Hadi",
  "Indra",
  "Joko",
  "Kemal",
  "Lukman",
  "Maulana",
  "Nugroho",
  "Oscar",
  "Pratama",
  "Qasim",
  "Rizki",
  "Satria",
  "Tegar",
];
export const subjects = [
  "Aku",
  "Kucing",
  "Pohon",
  "Sahabat",
  "Laptop",
  "Anjing",
  "Bunga",
  "Buku",
  "Mobil",
  "Gunung",
  "Pelangi",
  "Ikan",
  "Planet",
  "Robot",
  "Hujan",
  "Laut",
  "Api",
  "Bintang",
  "Matahari",
  "Bulan",
  "Angin",
  "Buaya",
  "Pulau",
  "Pisang",
  "Televisi",
  "Gelombang",
  "Kamera",
  "Sapi",
  "Harimau",
];
export const predicates = [
  "mengamati",
  "menemui",
  "menyentuh",
  "menyukai",
  "membaca",
  "mendengarkan",
  "mengejar",
  "menyelinap",
  "melihat",
  "merenung",
  "memasak",
  "menari",
  "mengagumkan",
  "menghancurkan",
  "menggambar",
  "menggunakan",
  "menghargai",
  "menciptakan",
  "memperbaiki",
  "menyanyi",
  "mencium",
  "melompat",
  "membuat",
  "menghias",
  "memandang",
  "memanjat",
  "menggoda",
  "melupakan",
  "menghancurkan",
];
export const objects = [
  "langit",
  "buku",
  "makanan",
  "senyum",
  "pantai",
  "air",
  "kebahagiaan",
  "kesedihan",
  "kehidupan",
  "waktu",
  "alam",
  "keajaiban",
  "mimpi",
  "kebenaran",
  "cinta",
  "kesunyian",
  "hati",
  "dunia",
  "kegelapan",
  "keindahan",
  "kebebasan",
  "hujan",
  "bintang",
  "api",
  "angin",
  "awan",
  "kesabaran",
  "kebijaksanaan",
  "keberanian",
  "kebahagiaan",
];
export const adverbs = [
  "dengan senang hati",
  "secara cepat",
  "dengan penuh semangat",
  "tanpa ragu",
  "dengan santai",
  "dengan kegembiraan",
  "dengan kecintaan",
  "dengan cermat",
  "dengan kehormatan",
  "dengan kebijaksanaan",
  "dengan penuh perhatian",
  "dengan kekaguman",
  "dengan kekuatan",
  "dengan kelembutan",
  "dengan semangat",
  "dengan keterbukaan",
  "dengan kegembiraan",
  "dengan kejujuran",
  "dengan kehangatan",
  "dengan ketenangan",
  "dengan ketulusan",
  "dengan kebijakan",
  "dengan kreativitas",
  "dengan keberanian",
  "dengan keteguhan",
  "dengan keindahan",
  "dengan kebijaksanaan",
  "dengan ketekunan",
  "dengan kerendahan hati",
];
export const emailProvider = [
  "gmail.com",
  "yahoo.com",
  "outlook.com",
  "protonmail.com",
  "zoho.com",
];
